### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by batterseapower**
This builds on the work by @JamesRamm in PR #38 to fix issue #24.

With these changes, I can build the library successfully with the VS2015 x64 toolchain and all the tests pass.

### CODE REVIEW

**Comment by batterseapower** [comment]
Looks like those Travis failures are both timeouts? I did notice the tests are very slow but I don't think that's caused by my changes.

**Comment by deads** [comment]
The timeouts are only for Mac OS X, not Linux. As time goes on, the folks at Travis are squeezing more Mac builds on the same machine so that our Mac Travis jobs take much longer. This makes it difficult for us to calibrate our regression test suite for Mac on Travis. In the mean time, I have deactivated tests for Mac but left the compilation alone. This is a workaround until we come up with a different solution for regression testing.

So that we can test your pull request, can you please pull from master so that your branch has the necessary files to automatically run the tests?

```
git pull https://github.com/wiseio/paratext.git master
```

Once you do this pull, we can test your pull request.

**Comment by deads** [comment]
Thank you for your contributions. Your improvements have been incorporated into later pull requests. #54 supersedes this PR so I will close it.

**Comment by batterseapower** [comment]
Thanks!

**Pull request closed without merging**
