### PR TITLE
Work for #24 (Windows support)

### PR DESCRIPTION
**Pull request by JamesRamm**
This addresses windows support (#24) to the point that paratext is able to compile on windows using VS2015 (MSVC 1900) and python 3.5.

However, running on windows it just seems to hang when loading a csv, e.g:

```
paratext.load_csv_to_dict("file://C:/temp/exposures_105k_lines.csv")
```

Functionality on linux is unaltered - still works fine and the above call returns in a couple of seconds. If anyone has any ideas of what might be happening on windows that would be helpful!

### CODE REVIEW

**Comment by deads** [comment]
Hi James,

Thank you for your assistance in adding support for Windows. We have added regression tests and created a Travis build.

If you could re-pull from `master` (to get the Travis build configuration) and run your branch on Travis that would be great. I want to make sure the proposed changes don't break functionality on Linux and Mac OS X.

Best,
Damian

**Comment by flaviodrt** [comment]
Hi James,

I have installed from your branch but when I import paratext I'm getting this error:
`ImportError: No module named _paratext_internal`

Do you know how can I fix this?
Thanks

**Comment by deads** [comment]
Hi James,

The `_paratext_internal` refers to the `_paratext_internal.so`, which is the CPython wrapper to the C++ paratext guts. This `ImportError` has three possible causes:

1. your `PYTHONPATH` is not set to point to the location of the paratext libraries.
2. `_paratext_internal.so` was never built when running `python setup.py build install --prefix=/your/prefix`
3. you build `_paratext_internal.so` but never installed it.

So that we can test your pull request, can you please pull from master so that your branch has the necessary files to automatically run the tests?

```
git pull https://github.com/wiseio/paratext.git master
```

Once you do this pull, we can test your pull request.

Thank you!

Damian

**Comment by deads** [comment]
Thank you for your contributions. Your improvements have been incorporated into later pull requests. #54 supersedes this PR so I will close it.

**Pull request closed without merging**
