### PR TITLE
Support for URI filenames, unicode filenames, and unicode paramters

### PR DESCRIPTION
**Pull request by deads**
Hi,

As requested by @pdbaines, I added support for:
   - URI filenames (Issue #8), 
   - unicode filenames (Issue #7)

Damian

### CODE REVIEW

**Comment by pdbaines** [comment]
@deads -- looks like a permission error on setup.py:
```
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    init_py = open("paratext/__init__.py", "w")
IOError: [Errno 13] Permission denied: 'paratext/__init__.py'
```
and:
```
$ ls -alh paratext
total 32K
drwxrwxr-x 2 ubuntu ubuntu 4.0K Jun 13 23:53 .
drwxrwxr-x 4 ubuntu ubuntu 4.0K Jun 13 23:50 ..
-rw-rw-r-- 1 ubuntu ubuntu  15K Jun 13 23:53 core.py
-rw-rw-r-- 1 ubuntu ubuntu 2.4K Jun  8 06:34 helpers.py
-rw-r--r-- 1 root   root    150 Jun  8 07:08 __init__.py
```

**Comment by pdbaines** [comment]
Wait... that file wasn't even changed in this PR. Okay, ignore me... I have it up and running. I will dig in and let you know any issues that come up.

**Comment by deads** [comment]
Okay, great @pdbaines . Standing by.

**Comment by pdbaines** [comment]
All good. I'll merge.

**Pull request merged**
